@startuml
node Jackal as j #Orange
title Merge features
frame "Items to insert" as fr {
    collections "Source collections (-c)" as sc #cbff5c
    folder "Source folder (-f)" as f #cbff5c
}
file "Start file (-s)" as sf #94afd1
file "Blank" as b #White
artifact "Output file (-o)" as o #94afd1
f -[dashed]down-o j
sc -[dashed]down-o j
sf -right-> j
j -right-> o
b -[dashed]up-> j


@enduml